# docker-compose.yaml (postgres)
version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dss
      - POSTGRES_PASSWORD=dss
      - POSTGRES_DB=stand
    ports:
      - '5434:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./src/database:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    
    
volumes:
  db:
    driver: local